[project]
name = "metric-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.5",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.3",
]
